export const languageList = [
  { language: 'English' },
  { language: 'Mandarin Chinese' },
  { language: 'Spanish' },
  { language: 'Hindi' },
  { language: 'French' },
  { language: 'Arabic' },
  { language: 'Bengali' },
  { language: 'Russian' },
  { language: 'Portuguese' },
  { language: 'Urdu' },
  { language: 'Indonesian' },
  { language: 'German' },
  { language: 'Japanese' },
  { language: 'Swahili' },
  { language: 'Punjabi' },
  { language: 'Telugu' },
  { language: 'Turkish' },
  { language: 'Korean' },
  { language: 'Tamil' },
  { language: 'Italian' },
  { language: 'Vietnamese' },
  { language: 'Marathi' },
  { language: 'Ukrainian' },
  { language: 'Dutch' },
  { language: 'Polish' },
];

export const languageLevel = [
  { level: 'Beginner' },
  { level: 'Elementary' },
  { level: 'Intermediate' },
  { level: 'Upper-Intermediate' },
  { level: 'Advanced' },
  { level: 'Native' },
];
