export const countryList = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

export const countryListUa = [
  { name: 'Австралія', code: 'AU' },
  { name: 'Австрія', code: 'AT' },
  { name: 'Азербайджан', code: 'AZ' },
  { name: 'Албанія', code: 'AL' },
  { name: 'Алжир', code: 'DZ' },
  { name: 'Американське Самоа', code: 'AS' },
  { name: 'Ангілья', code: 'AI' },
  { name: 'Ангола', code: 'AO' },
  { name: 'Андорра', code: 'AD' },
  { name: 'Антарктида', code: 'AQ' },
  { name: 'Антигуа і Барбуда', code: 'AG' },
  { name: 'Аргентина', code: 'AR' },
  { name: 'Аруба', code: 'AW' },
  { name: 'Афганістан', code: 'AF' },
  { name: 'Багамські острови', code: 'BS' },
  { name: 'Бангладеш', code: 'BD' },
  { name: 'Барбадос', code: 'BB' },
  { name: 'Бахрейн', code: 'BH' },
  { name: 'Беліз', code: 'BZ' },
  { name: 'Бельгія', code: 'BE' },
  { name: 'Бенін', code: 'BJ' },
  { name: 'Бермуди', code: 'BM' },
  { name: 'Болгарія', code: 'BG' },
  { name: 'Болівія', code: 'BO' },
  { name: 'Боснія і Герцеговина', code: 'BA' },
  { name: 'Ботсвана', code: 'BW' },
  { name: 'Бразилія', code: 'BR' },
  { name: 'Британська територія в Індійському океані', code: 'IO' },
  { name: 'Бруней', code: 'BN' },
  { name: 'Буркіна-Фасо', code: 'BF' },
  { name: 'Бурунді', code: 'BI' },
  { name: 'Бутан', code: 'BT' },
  { name: 'Вануату', code: 'VU' },
  { name: 'Венесуела', code: 'VE' },
  { name: "В'єтнам", code: 'VN' },
  { name: 'Вірменія', code: 'AM' },
  { name: 'Габон', code: 'GA' },
  { name: 'Гаїті', code: 'HT' },
  { name: 'Гамбія', code: 'GM' },
  { name: 'Гана', code: 'GH' },
  { name: 'Гаяна', code: 'GY' },
  { name: 'Гваделупа', code: 'GP' },
  { name: 'Гватемала', code: 'GT' },
  { name: 'Гвінея', code: 'GN' },
  { name: 'Гвінея-Бісау', code: 'GW' },
  { name: 'Гернсі', code: 'GG' },
  { name: 'Гібралтар', code: 'GI' },
  { name: 'Гондурас', code: 'HN' },
  { name: 'Гонконг', code: 'HK' },
  { name: 'Гренада', code: 'GD' },
  { name: 'Гренландія', code: 'GL' },
  { name: 'Греція', code: 'GR' },
  { name: 'Грузія', code: 'GE' },
  { name: 'Гуам', code: 'GU' },
  { name: 'Данія', code: 'DK' },
  { name: 'Демократична Республіка Конго', code: 'CD' },
  { name: 'Джерсі', code: 'JE' },
  { name: 'Джибуті', code: 'DJ' },
  { name: 'Домініка', code: 'DM' },
  { name: 'Домініканська Республіка', code: 'DO' },
  { name: 'Еквадор', code: 'EC' },
  { name: 'Екваторіальна Гвінея', code: 'GQ' },
  { name: 'Еритрея', code: 'ER' },
  { name: 'Естонія', code: 'EE' },
  { name: 'Ефіопія', code: 'ET' },
  { name: 'Єгипет', code: 'EG' },
  { name: 'Ємен', code: 'YE' },
  { name: 'Замбія', code: 'ZM' },
  { name: 'Західна Сахара', code: 'EH' },
  { name: 'Зімбабве', code: 'ZW' },
  { name: 'Ізраїль', code: 'IL' },
  { name: 'Індія', code: 'IN' },
  { name: 'Індонезія', code: 'ID' },
  { name: 'Ірак', code: 'IQ' },
  { name: 'Іран, Ісламська Республіка', code: 'IR' },
  { name: 'Ірландія', code: 'IE' },
  { name: 'Ісландія', code: 'IS' },
  { name: 'Іспанія', code: 'ES' },
  { name: 'Італія', code: 'IT' },
  { name: 'Йорданія', code: 'JO' },
  { name: 'Кабо-Верде', code: 'CV' },
  { name: 'Казахстан', code: 'KZ' },
  { name: 'Кайманові острови', code: 'KY' },
  { name: 'Камбоджа', code: 'KH' },
  { name: 'Камерун', code: 'CM' },
  { name: 'Канада', code: 'CA' },
  { name: 'Катар', code: 'QA' },
  { name: 'Кенія', code: 'KE' },
  { name: 'Китай', code: 'CN' },
  { name: 'Кіпр', code: 'CY' },
  { name: 'Кірібаті', code: 'KI' },
  { name: 'Киргизстан', code: 'KG' },
  { name: 'Кокосові (Кілінгові) острови', code: 'CC' },
  { name: 'Колумбія', code: 'CO' },
  { name: 'Комори', code: 'KM' },
  { name: 'Конго', code: 'CG' },
  { name: 'Корейська Народно-Демократична Республіка', code: 'KP' },
  { name: 'Корея, Республіка', code: 'KR' },
  { name: 'Коста-Рика', code: 'CR' },
  { name: "Кот-д'Івуар", code: 'CI' },
  { name: 'Куба', code: 'CU' },
  { name: 'Кувейт', code: 'KW' },
  { name: 'Лаоська Народно-Демократична Республіка', code: 'LA' },
  { name: 'Латвія', code: 'LV' },
  { name: 'Лесото', code: 'LS' },
  { name: 'Ліберія', code: 'LR' },
  { name: 'Ліван', code: 'LB' },
  { name: 'Лівійська Арабська Джамахірія', code: 'LY' },
  { name: 'Ліхтенштейн', code: 'LI' },
  { name: 'Литва', code: 'LT' },
  { name: 'Люксембург', code: 'LU' },
  { name: 'Маврикій', code: 'MU' },
  { name: 'Мавританія', code: 'MR' },
  { name: 'Мадагаскар', code: 'MG' },
  { name: 'Майотта', code: 'YT' },
  { name: 'Макао', code: 'MO' },
  { name: 'Македонія, колишня югославська республіка', code: 'MK' },
  { name: 'Малаві', code: 'MW' },
  { name: 'Малайзія', code: 'MY' },
  { name: 'Малі', code: 'ML' },
  { name: 'Мальдіви', code: 'MV' },
  { name: 'Мальта', code: 'MT' },
  { name: 'Марокко', code: 'MA' },
  { name: 'Мартініка', code: 'MQ' },
  { name: 'Маршаллові острови', code: 'MH' },
  { name: 'Мексика', code: 'MX' },
  { name: 'Мозамбік', code: 'MZ' },
  { name: 'Молдова, Республіка', code: 'MD' },
  { name: 'Монако', code: 'MC' },
  { name: 'Монголія', code: 'MN' },
  { name: 'Монтсеррат', code: 'MS' },
  { name: "М'янма", code: 'MM' },
  { name: 'Намібія', code: 'NA' },
  { name: 'Науру', code: 'NR' },
  { name: 'Непал', code: 'NP' },
  { name: 'Нігер', code: 'NE' },
  { name: 'Нігерія', code: 'NG' },
  { name: 'Нідерланди', code: 'NL' },
  { name: 'Нідерландські Антильські острови', code: 'AN' },
  { name: 'Нікарагуа', code: 'NI' },
  { name: 'Німеччина', code: 'DE' },
  { name: 'Ніуе', code: 'NU' },
  { name: 'Нова Зеландія', code: 'NZ' },
  { name: 'Нова Каледонія', code: 'NC' },
  { name: 'Норвегія', code: 'NO' },
  { name: "Об'єднані Арабські Емірати", code: 'AE' },
  { name: 'Оландські острови', code: 'AX' },
  { name: 'Оман', code: 'OM' },
  { name: 'Острів Буве', code: 'BV' },
  { name: 'Острів Норфолк', code: 'NF' },
  { name: 'Острів Мен', code: 'IM' },
  { name: 'Острів Херд і Острови Макдональд', code: 'HM' },
  { name: 'Острови Кука', code: 'CK' },
  { name: 'Пакистан', code: 'PK' },
  { name: 'Палау', code: 'PW' },
  { name: 'Палестинська територія, окупована', code: 'PS' },
  { name: 'Панама', code: 'PA' },
  { name: 'Папуа-Нова Гвінея', code: 'PG' },
  { name: 'Парагвай', code: 'PY' },
  { name: 'Перу', code: 'PE' },
  { name: 'Південна Африка', code: 'ZA' },
  { name: 'Південна Георгія і Південні Сандвічеві острови', code: 'GS' },
  { name: 'Північні Маріанські острови', code: 'MP' },
  { name: 'Піткерн', code: 'PN' },
  { name: 'Польща', code: 'PL' },
  { name: 'Португалія', code: 'PT' },
  { name: 'Пуерто-Ріко', code: 'PR' },
  { name: 'Реюньйон', code: 'RE' },
  { name: 'Різдвяні острови', code: 'CX' },
  { name: 'Руанда', code: 'RW' },
  { name: 'Румунія', code: 'RO' },
  { name: 'Сальвадор', code: 'SV' },
  { name: 'Самоа', code: 'WS' },
  { name: 'Сан-Марино', code: 'SM' },
  { name: 'Сан-Томе і Принсіпі', code: 'ST' },
  { name: 'Саудівська Аравія', code: 'SA' },
  { name: 'Свазіленд', code: 'SZ' },
  { name: 'Свалбард і Ян-Маєн', code: 'SJ' },
  { name: 'Свята Єлена', code: 'SH' },
  { name: 'Святий Престол (Ватикан)', code: 'VA' },
  { name: 'Сейшели', code: 'SC' },
  { name: 'Сенегал', code: 'SN' },
  { name: 'Сент-Вінсент і Гренадини', code: 'VC' },
  { name: 'Сент-Кіттс і Невіс', code: 'KN' },
  { name: 'Сент-Люсія', code: 'LC' },
  { name: "Сент-П'єр і Мікелон", code: 'PM' },
  { name: 'Сербія і Чорногорія', code: 'CS' },
  { name: 'Сінгапур', code: 'SG' },
  { name: 'Сирійська Арабська Республіка', code: 'SY' },
  { name: 'Словаччина', code: 'SK' },
  { name: 'Словенія', code: 'SI' },
  { name: 'Соломонові острови', code: 'SB' },
  { name: 'Сомалі', code: 'SO' },
  {
    name: 'Сполучене Королівство Великої Британії і Північної Ірландії',
    code: 'GB',
  },
  { name: 'Сполучені Штати', code: 'US' },
  { name: 'Сполучені Штати Вірджинії', code: 'VI' },
  { name: 'Судан', code: 'SD' },
  { name: 'Сурінам', code: 'SR' },
  { name: 'Східний Тимор', code: 'TL' },
  { name: 'Сьєрра-Леоне', code: 'SL' },
  { name: 'Таджикистан', code: 'TJ' },
  { name: 'Таїланд', code: 'TH' },
  { name: 'Тайвань', code: 'TW' },
  { name: "Танзанія, Об'єднана Республіка", code: 'TZ' },
  { name: 'Теркс і Кайкос', code: 'TC' },
  { name: 'Того', code: 'TG' },
  { name: 'Токелау', code: 'TK' },
  { name: 'Тонга', code: 'TO' },
  { name: 'Тринідад і Тобаго', code: 'TT' },
  { name: 'Тувалу', code: 'TV' },
  { name: 'Туніс', code: 'TN' },
  { name: 'Туреччина', code: 'TR' },
  { name: 'Туркменістан', code: 'TM' },
  { name: 'Уганда', code: 'UG' },
  { name: 'Угорщина', code: 'HU' },
  { name: 'Узбекистан', code: 'UZ' },
  { name: 'Україна', code: 'UA' },
  { name: 'Уолліс і Футуна', code: 'WF' },
  { name: 'Уругвай', code: 'UY' },
  { name: 'Фарерські острови', code: 'FO' },
  { name: 'Федеративні Штати Мікронезії', code: 'FM' },
  { name: 'Фіджі', code: 'FJ' },
  { name: 'Філіппіни', code: 'PH' },
  { name: 'Фінляндія', code: 'FI' },
  { name: 'Фолклендські острови (Мальвінські)', code: 'FK' },
  { name: 'Франція', code: 'FR' },
  { name: 'Французька Гвіана', code: 'GF' },
  { name: 'Французькі Південні території', code: 'TF' },
  { name: 'Французька Полінезія', code: 'PF' },
  { name: 'Хорватія', code: 'HR' },
  { name: 'Центральноафриканська Республіка', code: 'CF' },
  { name: 'Чад', code: 'TD' },
  { name: 'Чеська Республіка', code: 'CZ' },
  { name: 'Чилі', code: 'CL' },
  { name: 'Швейцарія', code: 'CH' },
  { name: 'Швеція', code: 'SE' },
  { name: 'Шрі-Ланка', code: 'LK' },
  { name: 'Ямайка', code: 'JM' },
  { name: 'Японія', code: 'JP' },
];
