export const skillsList = [
  { skill: 'Administrative Support' },
  { skill: 'Carpentry/Woodworking' },
  { skill: 'Communication Skills' },
  { skill: 'Community Outreach' },
  { skill: 'Content Writing' },
  { skill: 'Photography' },
  { skill: 'Project Management' },
  { skill: 'Cooling/Catering' },
  { skill: 'Psychological Support' },
  { skill: 'Data Analysis' },
  { skill: 'Public Speaking' },
  { skill: 'Research' },
  { skill: 'Data Entry' },
  { skill: 'Driving/Transportation' },
  { skill: 'Sewing/Textile Work' },
  { skill: 'Social Media Management' },
  { skill: 'Event Planning' },
  { skill: 'First Aid/CPR' },
  { skill: 'Teaching/Tutoring' },
  { skill: 'Fitness/Physical Training' },
  { skill: 'Technical Support' },
  {
    skill: 'Translation (Specify Languages)',
  },
  { skill: 'Fundraising' },
  { skill: 'Gardening/Landscaping' },
  { skill: 'Videography' },
  { skill: 'Grant Writing' },
  { skill: 'Graphic Design' },
  { skill: 'Marketing' },
  { skill: 'Mentoring/Coaching' },
  { skill: 'Painting/Decorating' },
  { skill: 'Web Development' },
];
